services:
  # Frontend Service (Next.js)
  - type: web
    name: homy-frontend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: AIzaSyCv01ZQAkJF5SC_y7UQWI-73u9uxisk6j8
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: homy-auth1.firebaseapp.com
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: homy-auth1
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: homy-auth1.firebasestorage.app
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: 595109350511
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: 1:595109350511:web:686dbc363e7da9493d119a
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        value: G-9RL8C7QWQJ
